Provide the ability to upload patches #78
xwikisas/application-admintools pull request #104
Opened 2024-10-10 13:52 UTC by ChiuchiuSorin

Created new endpoints for the package upload operation and refactored the healthCheckJob code to be usable by multiple job.

The import package page: 
![importPage](https://github.com/user-attachments/assets/696af215-c791-4825-a645-15b5db34dd3d)

The import package result:  
![packageUpload](https://github.com/user-attachments/assets/144f84ac-e097-4f0a-b954-6fe3797e6340)

The modification for file section: 
![filesSection](https://github.com/user-attachments/assets/f0af6984-1af1-4a3e-8c43-cf88eb2ac040)

2024-10-10 13:53 UTC, ChiuchiuSorin commented
There are no tests added yet, I will add them in a future commit.

2025-02-05 10:49 UTC, trrenty requested changes

2025-02-05 10:49 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJob.java
> +                    throw new RuntimeException(
Could log the error instead. Are you ok with terminating the job if one file could not be deleted? Maybe you would be interested in continuing with the other files

2025-02-05 10:49 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJob.java
> +}
All these additional code lines makes the file convoluted and harder to follow. I'll take another look on this after you change the logging process as suggested. 

As a note, you should log more information for this job. Like "starting the batch save", "failed batch save. Starting batch restore". Things like these.

2025-02-05 10:49 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
> +    public static final String NEW_FILE_PATH_FORMAT = "%s/%s";
Shouldnt hard code path formats, since they might not behave as you expect on all platforms.

2025-02-05 10:49 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
> +            String extension = filePath.substring(filePath.lastIndexOf("."));
Could `lastIndexOf` return -1? (if there is a file without extension) In this case, the `substring` method will throw an IndexOutOfBounds exception.

2025-02-05 10:49 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
> +            baos.write(buffer, 0, len);
This is not a good idea. You seem to be storing the content of the files in memory. This can lead to OutOfMemory quite easily. I dont think you need to store the content of the file right now. You can simply open it and process the content when you need it.

2025-02-05 10:49 UTC, trrenty commented on application-admintools-default/src/test/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessorTest.java
> +        targetDir = new File(tmpDir, "target_folder/");
```suggestion
        targetDir = new File(tmpDir, "target_folder");
```
Is the slash needed? I'm not sure how it will behave on windows, for example. The tests might as well fail.

2025-02-05 10:49 UTC, trrenty commented on application-admintools-ui/src/main/resources/AdminTools/Code/PackageUploadSheet.xml
> +  #set ($translationPrefix = 'adminTools.jobs.upload')
shouldnt this end in '.'?

2025-02-17 11:28 UTC, ChiuchiuSorin commented on application-admintools-api/src/main/java/com/xwiki/admintools/jobs/PackageUploadJobRequest.java
> +        setDefaultId();
Admin tools is used as root, and for the upload jobs that I'm creating, I'm using the attachment reference and startTime of the job to create the job ID, this way the jobs are unique.

2025-02-20 11:02 UTC, ChiuchiuSorin commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/data/identifiers/AbstractServerInfo.java
> +        for (String xwikiLibraryFolderPath : this.xwikiInstallPossiblePaths) {
I did the improvement, if you think the modification is too unrelated or large, I will do a different PR.

2025-02-20 11:16 UTC, ChiuchiuSorin commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJob.java
> +@Unstable
It should be using [PER_LOOKUP](https://github.com/xwikisas/xwiki-commons/blob/419eaec6f43729238c2e1672f50b280e48747cd3/xwiki-commons-core/xwiki-commons-job/xwiki-commons-job-default/src/main/java/org/xwiki/job/internal/AbstractJob.java#L36) instantiation strategy from `AbstractJob`.

2025-02-20 11:47 UTC, ChiuchiuSorin commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJob.java
> +                    throw new RuntimeException(
I discussed this with Lavinia early in development and considering that the upload might involve essential files, the best way to do this is to be cautious and abort the upload if any error occurs.

2025-03-05 14:31 UTC, trrenty requested changes

2025-03-05 14:31 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
>              baos.write(buffer, 0, len);
this still loads everything to memory https://github.com/AdoptOpenJDK/openjdk-jdk11/blob/master/src/java.base/share/classes/java/io/ByteArrayOutputStream.java#L154

you should try read your buffer, write to new location, repeat. So only 1024 bytes will be stored in memory at a time

2025-03-05 14:31 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
>              baos.write(buffer, 0, len);
I also think you can have a greater size for the buffer. but i'm not entirely sure what would be a good size.

2025-03-21 12:44 UTC, ChiuchiuSorin commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
> +        try (OutputStream fos = new FileOutputStream(targetFile, false)) {
Yes, the target file is backed up previously (see [line 107](https://github.com/xwikisas/application-admintools/pull/104/files#diff-884eacbccfe6d55dc16577572f0f85440047ec3cab8fd5e43bbbaba9293fdf47R107) from uploadJob). The renaming is done because some files that are uploaded may modify the name. For example 
from: `xwiki-commons-xml-14.10.2.jar`
to: `xwiki-commons-xml-14.10.2-clients-683edb2d40f44f25e245f0abf833bf52a026eb2d.jar`

2025-03-25 12:45 UTC, ChiuchiuSorin commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJobFileProcessor.java
> +        try (OutputStream fos = new FileOutputStream(targetFile, false)) {
After discussion notes:
* should check if the `targetFile.exists()` check is necessary -  after testing I removed it and replaced it with a name check.
* should add logger debug messages in case of an error.

2025-03-25 13:09 UTC, trrenty requested changes
It would be better to log the messages at `info` level.

2025-03-25 13:09 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/uploadJob/UploadJob.java
> +            logger.debug("Finished upload job with ID: [{}]", this.status.getJobID());
i think it would be better to have "info" level logs. The debug level is used for debugging purposes and can print more detailed information.

2025-03-26 09:43 UTC, trrenty requested changes

2025-03-26 09:43 UTC, trrenty commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/rest/DefaultAdminToolsResource.java
> +                return Response.status(102).build();
After a live discussion, we have the following remarks:

* The javascript that calls this endpoint should disable itself once clicked, so there is no possibility of 2 jobs to be run by mistake. (clicking twice)
* should check whether changing the job group will make different jobs runs sequentially rather than in parallel. i.e. running 2 jobs for 2 different files will wait for one another

2025-03-31 06:50 UTC, trrenty approved these changes

2025-04-15 12:40 UTC, merged