Add recycle bin operations #33
xwikisas/application-admintools pull request #34
Opened 2023-12-05 15:53 UTC by ChiuchiuSorin

Create a hyperlink inside the Health Check section that allows the user to view all wikis recycle bins and perform actions over them.

2023-12-06 12:13 UTC, ChiuchiuSorin commented
* Health check shrink recycle bin modal: 
![image](https://github.com/xwikisas/application-admintools/assets/104432589/54f53010-a1a4-4293-95f2-f958998a7942)

* Wiki recycle bin page: 
![image](https://github.com/xwikisas/application-admintools/assets/104432589/03e11e1b-841f-4b42-9788-d751d4480290)

There is the same view for deleted attachments, but it's missing the `Delete all` button.

2024-02-20 11:36 UTC, ChiuchiuSorin commented
There is no longer a dedicated page inside Admin tools to view the recycle bin. The modal now has hyperlinks for each wiki to Page Index document, with a specific tab being preselected depending on the category (pages or attachments).
![image](https://github.com/xwikisas/application-admintools/assets/104432589/5b12058f-fbc5-4e06-8902-0e5591d5c160)

2024-02-21 15:32 UTC, oanalavinia requested changes

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-api/src/main/java/com/xwiki/admintools/health/WikiRecycleBinResult.java
> +    public long getPageSize()
WDYT about `getDocumentsCount`?

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-api/src/main/java/com/xwiki/admintools/health/WikiRecycleBinResult.java
> +    public long getAttachmentSize()
WDYT about `getAttachmentsCount`?

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/health/operations/RecycleBinOperations.java
> +public class RecycleBinOperations
`RecycleBinsManager` WDYT?

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/AdminToolsManager.java
> +    public List<WikiRecycleBinResult> getWikisRecycleBinSize() throws QueryException, WikiManagerException
`Bins` should be used

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/health/operations/RecycleBinOperations.java
> +    public List<WikiRecycleBinResult> getAllWikisRecycleBinInfo() throws QueryException, WikiManagerException
Maybe `getWikisRecycleBins`? Or `getWikisRecycleBinsSize`, to have it similar to the method where is used

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Macros.xml
> +                  #set ($wikiRecycleReference = "${wikiBin.getWikiId()}:Main.AllDocs")
`#set ($allDocsRef = $services.model.createDocumentReference('wikiId', 'Main', 'AllDocs'))`

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Macros.xml
> +                      &lt;a href="${xwiki.getURL($wikiRecycleReference)}?view=deletedDocs" target="_blank"&gt;
```
${xwiki.getURL($allDocsRef, 'view', $escapetool.url({'view': 'deletedDocs'}))}
```

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Macros.xml
> +                      &lt;a href="${xwiki.getURL($wikiRecycleReference)}?view=deletedAttachments" target="_blank"&gt;
Same

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Translations.xml
> +adminTools.dashboard.healthcheck.modal.wikiBins.header.page=Page recycle bin
`Deleted pages`

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Translations.xml
> +adminTools.dashboard.healthcheck.modal.wikiBins.header.attach=Attachment recycle bin
`Deleted attachments`

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Translations.xml
> +adminTools.dashboard.healthcheck.modal.wikiBins.title=Wikis recycle bin (number of documents)
`Recycle bins size for all wikis`

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Translations.xml
> +adminTools.dashboard.healthcheck.modal.wikiBins.error=There has been an error while gathering info about your instance wikis recycle bin size.
`There has been an error while gathering recycle bins size info for all wikis.`

2024-02-21 15:32 UTC, oanalavinia commented on application-admintools-default/src/main/resources/templates/wikiSizeTemplate.vm
> +          <li><a href="#viewWikisRecycleBinModal" data-toggle="modal" data-target="#viewWikisRecycleBinModal">
You are also missing a title for this link

2024-02-22 09:26 UTC, oanalavinia commented on application-admintools-default/src/main/resources/templates/wikiSizeTemplate.vm
> +          <li><a href="#viewWikisRecycleBinModal" data-toggle="modal" data-target="#viewWikisRecycleBinModal">
You should add a title to this element, so when the user hovers over it he will get more info about what it does

2024-02-22 10:39 UTC, ChiuchiuSorin commented
The look of the modal with the explanatory text. 
![image](https://github.com/xwikisas/application-admintools/assets/104432589/9a2509ad-afe8-4b29-9059-62087f1f39a0)

2024-02-22 15:29 UTC, oanalavinia reviewed
Almost done:)

2024-02-22 15:29 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/wikiUsage/RecycleBinsManager.java
> +            result.setDocumentsCount(getNumberOfDeletedDocuments(wikiId, "XWikiDeletedDocument"));
This is just more like a suggestion
You could add a `getWikiRecycleBinsSize` method to create the `WikiRecycleBins` object for this wiki, to separate things. Then you can have here only `results.add(getWikiRecycleBinsSize(wikiDescriptor.getId))`
To go even further, you can write this `for` as:
```
wikiDescriptorManager.getAll().stream()
  .forEach(wiki -> results.add(getWikiRecycleBinsSize(wiki.getId)));
```
Might need some adjustments

2024-02-22 15:29 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/wikiUsage/RecycleBinsManager.java
> +     * @return info about all existing wikis in instance.
`Get instance recycle bins info, like deleted documents and attachment.`

`@return a {@link List} of {@link WikiRecycleBins} objects containing recycle bins info for each wiki of the instance`

2024-02-22 15:29 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/internal/AdminToolsManager.java
> +     * @return info about all existing wikis in instance.
This needs an update as well, check comment on RecycleBinsManager

2024-02-22 15:29 UTC, oanalavinia commented on application-admintools-default/src/main/java/com/xwiki/admintools/script/AdminToolsScriptService.java
> +     * @return a {@link List} with wikis recycle bin info or null in case of an error.
This needs an update as well, check comment on RecycleBinsManager

2024-02-22 15:29 UTC, oanalavinia commented on application-admintools-ui/src/main/resources/AdminTools/Code/Translations.xml
> +adminTools.dashboard.showLogs=View last n lines of log...
Duplicated key

2024-02-27 08:36 UTC, oanalavinia approved these changes

2024-02-27 09:01 UTC, merged